apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productcatalog-virtualservice
spec:
  hosts:
    - productcatalog-k-service
  http:
  - route:
    - destination:
        host: productcatalog-k-service
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productcatalog-dr
spec:
  host: productcatalog-k-service
  subsets:
  - name: v1
    labels:
      app: productcatalogapp
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 1
        http:
          http1MaxPendingRequests: 1
          maxRequestsPerConnection: 1
      outlierDetection:
         consecutive5xxErrors: 1
         interval: 1s
         baseEjectionTime: 3m
         maxEjectionPercent: 100          